[tool.poetry]
name = "vss365today-finder"
version = "1.0.0"
description = "#vss365 today prompt tweet finder service"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
apscheduler = "^3.10.1"
requests = "^2.28.2"
tweepy = "^4.13.0"
sys-vars = "^5.0.0"
pytz = "^2023.2"
py7zr = "^0.20.4"

[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
mypy = "^1.1"
black = "^23.3"
types-pytz = "^2023.2.0"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
