[tool.poetry]
name = "vss365today-finder"
version = "1.0.0"
description = "#vss365 today prompt tweet finder service"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
apscheduler = "^3.8.1"
requests = "^2.26.0"
tweepy = "^4.3.0"
sys-vars = "^4.0.3"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.910"
black = "^21.11b0"
types-pytz = "^2021.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
