[tool.poetry]
name = "vss365today-finder"
version = "1.0.0"
description = "#vss365 today prompt tweet finder service"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
apscheduler = "^3.9.1"
requests = "^2.27.1"
tweepy = "^4.7.0"
sys-vars = "^4.0.3"
pytz = "^2022.1"
py7zr = "^0.18.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.942"
black = "^22.1"
types-pytz = "^2021.3.6"
types-requests = "^2.27.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
