[tool.poetry]
name = "vss365today-finder"
version = "1.0.0"
description = "#vss365 today prompt tweet finder service"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
apscheduler = "^3.8.1"
requests = "^2.27.1"
tweepy = "^4.4.0"
sys-vars = "^4.0.3"
pytz = "^2021.1"
py7zr = "^0.17.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.930"
black = "^21.12b0"
types-pytz = "^2021.3.4"
types-requests = "^2.27.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
