[tool.poetry]
name = "vss365today-finder"
version = "1.0.0"
description = "#vss365 today prompt tweet finder service"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
apscheduler = "^3.9.1"
requests = "^2.28.1"
tweepy = "^4.10.1"
sys-vars = "^4.0.3"
pytz = "^2022.2"
py7zr = "^0.20.0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
mypy = "^0.981"
black = "^22.8"
types-pytz = "^2022.2.1"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
